version: '3.9'

networks:
    network:

services:
    php:
        build:
            args:
                user: ${APP_USER}
                group: ${APP_GROUP}
            context: ./docker/php
            dockerfile: Dockerfile
        container_name: ${APP_NAME}_php
        volumes:
            - ./:/var/www/html
        ports:
            - "9000:9000"
            - "3000:3000"
        networks:
            - network
    mysql:
        image: mariadb:10.8.3
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3306:3306"
        networks:
            - network
    nginx:
        image: nginx:stable-alpine
        container_name: ${APP_NAME}_nginx
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
        networks:
            - network
    adminer:
        image: adminer
        restart: unless-stopped
        ports:
            - "8080:8080"
        networks:
            - network
